### PR TITLE
PLAN-949 Fixed so that the responses are filtered by the id of the person passed in

### PR DESCRIPTION
**Pull request by balen**

### CODE REVIEW

**Comment by Gailbear** [comment]
i suspect this needs some fixing because if the param changes this won't catch it

**Comment by Gailbear** [comment]
I'll take a hack at it tonight

**Comment by balen** [comment]
The parameter is not kept in the store and is always taken from the get param of the route. Changing page and going back to responses changes the param. The person id is assumed to be null.

The defaultFilter is a property of the table mixin. If there are any queries (search) the querys are merged with the default filter using the table mixin's mergeFilters. This has also been used in the session ranking and other places for a while.

**Comment by balen** [comment]
Merging, then we will fix bugs if any after testing in staging

**Pull request merged**
